[build]
  # Build command (if using a build process)
  # command = "npm run build"
  
  # Publish directory (where your built files are located)
  publish = "."
  
  # Functions directory for serverless functions
  functions = "netlify/functions"

# Redirects for API calls and SPA routing
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Handle client-side routing for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://cdn.jsdelivr.net https://cdnjs.cloudflare.com https://www.google-analytics.com https://connect.facebook.net; style-src 'self' 'unsafe-inline' https://cdn.jsdelivr.net https://fonts.googleapis.com https://cdnjs.cloudflare.com; font-src 'self' https://fonts.gstatic.com https://cdnjs.cloudflare.com; img-src 'self' data: https:; connect-src 'self' https://*.supabase.co https://www.google-analytics.com; frame-src https://www.google.com;"

# Cache static assets
[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.jpeg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.gif"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.svg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.ico"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Don't cache HTML files
[[headers]]
  for = "*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# Environment variables (these should be set in Netlify dashboard)
[context.production.environment]
  SUPABASE_URL = "your-production-supabase-url"
  SUPABASE_ANON_KEY = "your-production-supabase-anon-key"

[context.deploy-preview.environment]
  SUPABASE_URL = "your-staging-supabase-url"
  SUPABASE_ANON_KEY = "your-staging-supabase-anon-key"

# Build plugins (if needed)
# [[plugins]]
#   package = "@netlify/plugin-lighthouse"
#   [plugins.inputs]
#     audits = "performance,accessibility,best-practices,seo"

# Form handling (if using Netlify Forms as fallback)
[context.production.environment]
  NETLIFY_FORMS_ENABLED = "true"

# Analytics (optional)
[context.production.environment]
  GOOGLE_ANALYTICS_ID = "your-google-analytics-id"
  FACEBOOK_PIXEL_ID = "your-facebook-pixel-id"
